name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    outputs:
      semver: ${{ steps.gitversion.outputs.semver }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Restore dependencies
      run: dotnet restore 
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    # Make SemVer from GitVersion available as GitHub Action
    # variable.
    - name: Store SemVer
      id: gitversion
      run: |
        Get-ChildItem env:* | Sort-Object Name | Format-Table -AutoSize | Out-String -Width 900
        Write-Host "::set-output name=semver::$($env:GitVersion_SemVer)"

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    
    - name: NuGet
      run: dotnet pack --no-restore --configuration Release

    - name: Upload NuGet Packages
      uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: |
          nuget

    - name: Release
      if: github.ref == 'refs/heads/master'
      uses: ThomasPiskol/action-gh-release@892e2fa87d9e1881cfdbc34f2110bbbc299c8561
      with:
        tag_name: v${{ steps.gitversion.outputs.semver }}
        name: ${{ steps.gitversion.outputs.semver }}
        target_commitish: ${{github.sha}}
        draft: true
        prerelease: false
        body: |
          ${{ github.event.head_commit.message }}
        files: |
          nuget/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}